name: agrovet_pos
environment:
  sdk: '>=3.9.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  printing: ^5.11.0
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2
  fl_chart: ^1.1.1
  mobile_scanner: ^3.5.4
  image_picker: ^1.0.7
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
